const http=require('http');
const crypto=require('crypto');
const PORT=Number(process.env.PORT||10000), HOST='0.0.0.0';
const PUBLIC_KEY=String(process.env.DISCORD_PUBLIC_KEY||'').trim();
const BOT_TOKEN=String(process.env.DISCORD_TOKEN||'').trim();
const CLIENT_ID=String(process.env.CLIENT_ID||'').trim();
const GUILD_ID=String(process.env.GUILD_ID||'').trim();
const MAX_BODY=1024*1024;
const COMMANDS=[
['help','Show HOODZONE help'],['ping','Check endpoint latency'],['status','Show HOODZONE status'],['botinfo','Show bot information'],['serverinfo','Show server information'],['uptime','Show service uptime'],['dashboard','Show control center'],['setup','Show setup guide'],['permissions','Show required permissions'],['config','Show safe configuration status'],
['warn','Warn a member'],['warnings','View member warnings'],['clearwarns','Clear member warnings'],['timeout','Timeout a member'],['untimeout','Remove a timeout'],['kick','Kick a member'],['ban','Ban a member'],['unban','Unban a user'],['purge','Delete recent messages'],['modlogs','Show moderation logs'],['case','Show a moderation case'],['reason','Set a case reason'],['history','Show member history'],['report','Report a member'],['reports','Show reports'],['automod','Show AutoMod guidance'],['antispam','Show anti-spam status'],['antilink','Show anti-link status'],['antiraid','Show anti-raid status'],['lock','Lock a channel'],['unlock','Unlock a channel'],
['safety','Show safety controls'],['antibullying','Show anti-bullying controls'],['review','Review a safety report'],['deescalate','Send a de-escalation response'],['incident','Create an incident note'],['incidents','Show incident records'],['appeal','Submit an appeal'],['appeals','Show appeal status'],['reportuser','Report bullying or harassment'],['safetylog','Show safety logging status'],
['welcome','Show welcome setup'],['goodbye','Show goodbye setup'],['verify','Show verification setup'],['intro','Show introduction setup'],['rules','Show server rules'],['userinfo','Show user information'],['profile','Show profile information'],['avatar','Show user avatar'],['roles','List server roles'],['roleinfo','Show role information'],
['role','Manage a member role'],['createrole','Create a role'],['autorole','Show autorole setup'],['selfroles','Show self-role setup'],['reactionroles','Show reaction-role setup'],['staffroles','Show staff hierarchy'],['rolelock','Show role lock setup'],['rolelog','Show role logging'],['vip','Show VIP guidance'],['og','Show OG guidance'],
['daily','Claim daily points'],['coinflip','Flip a virtual coin'],['dice','Roll a die'],['trivia','Start trivia'],['quiz','Start a quiz'],['rps','Play rock paper scissors'],['numberguess','Play number guess'],['wordgame','Play word game'],['memory','Play memory'],['duel','Challenge a member'],
['balance','Show point balance'],['givepoints','Give points'],['leaderboard','Show leaderboard'],['rank','Show rank'],['level','Show level'],['xp','Show XP'],['rewards','Show rewards'],['shop','Show virtual shop'],['buy','Buy an item'],['inventory','Show inventory'],
['event','Create an event'],['events','List events'],['giveaway','Create a giveaway'],['poll','Create a poll'],['suggest','Submit a suggestion'],['suggestions','Show suggestions'],['ticket','Open a support ticket'],['afk','Set AFK status'],['remind','Create a reminder'],['announce','Create an announcement'],
['logs','Show logging setup'],['backup','Show safe configuration backup'],['maintenance','Show maintenance mode'],['staff','Show staff guidance'],['servermute','Mute a member'],['serverunmute','Unmute a member'],['nick','Set a member nickname'],['slowmode','Set channel slowmode'],['channelinfo','Show channel information']
];
if(COMMANDS.length!==100||new Set(COMMANDS.map(x=>x[0])).size!==100)throw new Error('Expected exactly 100 unique commands');
function send(res,status,body,type='application/json; charset=utf-8'){const d=Buffer.from(typeof body==='string'?body:JSON.stringify(body));res.writeHead(status,{'Content-Type':type,'Content-Length':d.length,'Cache-Control':'no-store'});res.end(d)}
function readBody(req){return new Promise((resolve,reject)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n<=MAX_BODY)a.push(c)});req.on('end',()=>n>MAX_BODY?reject(new Error('body_too_large')):resolve(Buffer.concat(a)));req.on('error',reject)})}
function keyDer(hex){const raw=Buffer.from(hex,'hex');if(raw.length!==32)throw new Error('invalid_public_key');return Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),raw])}
function verify(req,body){const sig=req.headers['x-signature-ed25519'],ts=req.headers['x-signature-timestamp'];if(typeof sig!=='string'||typeof ts!=='string'||!/^[0-9a-f]{128}$/i.test(sig)||!/^[0-9a-f]{64}$/i.test(PUBLIC_KEY))return false;return crypto.verify(null,Buffer.concat([Buffer.from(ts),body]),{key:keyDer(PUBLIC_KEY),format:'der',type:'spki'},Buffer.from(sig,'hex'))}
async function discord(path,opts={}){if(!BOT_TOKEN)throw new Error('DISCORD_TOKEN missing');const r=await fetch('https://discord.com/api/v10'+path,{...opts,headers:{Authorization:'Bot '+BOT_TOKEN,'Content-Type':'application/json',...(opts.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(`Discord API ${r.status}: ${d?.message||t||'request failed'}`);return d}
async function register(){if(!BOT_TOKEN||!CLIENT_ID||!GUILD_ID){console.warn('[REGISTER] skipped: missing token/client/guild');return}const payload=COMMANDS.map(([name,description])=>({name,description,type:1}));const out=await discord(`/applications/${encodeURIComponent(CLIENT_ID)}/guilds/${encodeURIComponent(GUILD_ID)}/commands`,{method:'PUT',body:JSON.stringify(payload)});console.log(`[REGISTER] synced ${Array.isArray(out)?out.length:0} guild commands`)}
function response(text,ephemeral=false){return {type:4,data:{content:text,...(ephemeral?{flags:64}:{})}}}
function username(i){return String((i.member?.user||i.user||{}).username||'member').slice(0,80)}
function message(name,i){const u=username(i);const s={
help:'🏙️ **HOODZONE HELP**\n100 slash commands are installed across moderation, safety, roles, games, XP, community and administration.',
ping:'🏓 **Pong!** The HOODZONE interactions endpoint is online.',status:'🛡️ **HOODZONE STATUS**\n🟢 HTTP endpoint: online\n🔐 Signature validation: enabled',botinfo:'🤖 **HOODZONE v1.2**\nDiscord HTTP Interactions Endpoint\n100 guild slash commands',serverinfo:`🏙️ **HOODZONE SERVER**\nGuild ID: \`${GUILD_ID||'not configured'}\``,uptime:`⏱️ Uptime: **${Math.floor(process.uptime())} seconds**`,dashboard:'🎛️ **HOODZONE CONTROL CENTER**\nModeration • Safety • Roles • Games • XP • Community • Administration',rules:'📜 **HOODZONE RULES**\n1. Respect everyone.\n2. No bullying or harassment.\n3. No hate speech or threats.\n4. No spam or malicious links.\n5. No impersonation.\n6. Follow Discord rules.',antibullying:'🛡️ **ANTI-BULLYING**\nReports can be handled through interactions. Continuous message scanning requires a separate Gateway bot with the required intents.',safety:'🛡️ **SAFETY**\nDiscord request-signature validation is enabled.',permissions:'🔐 **PERMISSIONS**\nUse Discord command permissions to restrict moderation commands to staff.',report:`🚨 **Report received** from ${u}.`,reportuser:`🛡️ **Safety report received** from ${u}.`,appeal:`📨 **Appeal received** from ${u}.`,ticket:`🎫 **Ticket request received** from ${u}.`,welcome:'👋 **WELCOME**\nAutomatic member-event welcomes require a Gateway bot.',daily:'🎮 **Daily** interaction received. Persistent points require storage.',balance:'💰 **Balance** interaction received. Persistent balances require storage.',leaderboard:'🏆 **Leaderboard** interaction received. Persistent XP requires storage.'};return s[name]||`✅ **/${name}** received successfully.\n👤 ${u}`}
async function handle(i){if(i.type===1)return {type:1};if(i.type!==2)return response('🏙️ HOODZONE received your interaction.');const n=i.data?.name;if(!COMMANDS.some(x=>x[0]===n))return response('❌ Unknown command.',true);return response(message(n,i))}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/')return send(res,200,'HOODZONE Interactions Endpoint is online.','text/plain; charset=utf-8');if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:'HOODZONE',mode:'discord-interactions',uptime:Math.floor(process.uptime())});if(req.method!=='POST'||u.pathname!=='/interactions')return send(res,404,{error:'not_found'});if(!PUBLIC_KEY)return send(res,500,{error:'server_not_configured'});const body=await readBody(req);if(!verify(req,body))return send(res,401,{error:'invalid_request_signature'});let i;try{i=JSON.parse(body.toString())}catch{return send(res,400,{error:'invalid_json'})}return send(res,200,await handle(i))}catch(e){console.error('[ERROR]',e.stack||e.message);return send(res,500,{error:'internal_server_error'})}});
server.listen(PORT,HOST,async()=>{console.log(`[START] HOODZONE listening on ${HOST}:${PORT}`);console.log('[START] GET /health');console.log('[START] POST /interactions');try{await register()}catch(e){console.error('[REGISTER] failed:',e.message)}});
process.on('SIGTERM',()=>server.close(()=>process.exit(0)));process.on('SIGINT',()=>server.close(()=>process.exit(0)));module.exports=server;
